version: '3'

services:
  db:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql/data
    environment:
      MYSQL_DATABASE: "open_interview_development"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/open_interview
      - ./api/vendor/bundle:/open_interview/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: sh -c "cd open_interview && npm start"
    ports:
      - "8000:3000"
volumes:
  mysql-data:
    driver: local